apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
  labels:
    purpose: learning
spec:
  capacity:
    storage: 5Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    type: DirectoryOrCreate
    path: "/data/pv01"
