apiVersion: v1
kind: Service
metadata:
  name: web-app
  labels:
    app_name: getting-started
    purpose: learning
spec:
  type: NodePort
  selector:
    app_name: getting-started
    purpose: learning
  ports:
    - nodePort: 30008
      port: 80
      targetPort: 80