apiVersion: v1
kind: Pod
metadata:
  name: sidecar-sample
  labels:
    app_name: getting-started
    purpose: learning
spec:
  containers:
    - name: getting-started
      image: docker/getting-started
    - name: sidecar-container
      image: alpine # alpine is a simple Linux OS image
      command: ["/bin/sh"]
      args: ["-c", "while true; do date >> /var/log/app.txt; sleep 5;done"]